[versions]
ktor = "3.3.3"
kotlin = "2.2.21"
logback = "1.5.19"
kotlinxHtml = "0.10.1"
jetbrainsMarkdown = "0.7.3"

[libraries]
ktorNetworkTlsCertificates = { module = "io.ktor:ktor-network-tls-certificates", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktorServerCoreJvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktorServerResourcesJvm = { module = "io.ktor:ktor-server-resources-jvm", version.ref = "ktor" }
ktorServerHtmlBuilderJvm = { module = "io.ktor:ktor-server-html-builder-jvm", version.ref = "ktor" }
ktorServerNettyJvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
kotlinxHtml = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinxHtml" }
kotlinCss = { module = "org.jetbrains.kotlin-wrappers:kotlin-css", version = "2025.11.12" }
markdown = { module = "org.jetbrains:markdown", version.ref = "jetbrainsMarkdown" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref= "kotlin" }
ktorServerTestHostJvm = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
